// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enclave/api/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional: override default resources
	Vcpu          int32 `protobuf:"varint,2,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb      int32 `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartRequest) GetVcpu() int32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *StartRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "BOOTING", "READY", "FAILED"
	SocketPath    string                 `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

type ToolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ToolName       string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"` // e.g. "bash", "python"
	Input          string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	PolicyId       string                 `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ContextJson    string                 `protobuf:"bytes,6,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ToolRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ToolRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

type ToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	SyscallLogs   []*SyscallLog          `protobuf:"bytes,4,rep,name=syscall_logs,json=syscallLogs,proto3" json:"syscall_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ToolResponse) GetSyscallLogs() []*SyscallLog {
	if x != nil {
		return x.SyscallLogs
	}
	return nil
}

type SyscallLog struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Timestamp            int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix nanos
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`            // e.g. "openat"
	Args                 string                 `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`            // formatted args string
	Pid                  int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // ALLOWED, BLOCKED, ERROR
	SessionId            string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action               string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	MetadataJson         string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ExecutionId          string                 `protobuf:"bytes,9,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OriginKind           string                 `protobuf:"bytes,10,opt,name=origin_kind,json=originKind,proto3" json:"origin_kind,omitempty"`
	OriginConversationId string                 `protobuf:"bytes,11,opt,name=origin_conversation_id,json=originConversationId,proto3" json:"origin_conversation_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SyscallLog) Reset() {
	*x = SyscallLog{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallLog) ProtoMessage() {}

func (x *SyscallLog) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallLog.ProtoReflect.Descriptor instead.
func (*SyscallLog) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SyscallLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SyscallLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyscallLog) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *SyscallLog) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyscallLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyscallLog) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyscallLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyscallLog) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SyscallLog) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SyscallLog) GetOriginKind() string {
	if x != nil {
		return x.OriginKind
	}
	return ""
}

func (x *SyscallLog) GetOriginConversationId() string {
	if x != nil {
		return x.OriginConversationId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StopRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAuditLogsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                 // Optional: filter by session
	SinceTimestamp int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // Optional: nanoseconds epoch
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuditLogsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetAuditLogsRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

func (x *GetAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*SyscallLog          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuditLogsResponse) GetLogs() []*SyscallLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ApplyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PolicyYaml    string                 `protobuf:"bytes,2,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyRequest) Reset() {
	*x = ApplyPolicyRequest{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyRequest) ProtoMessage() {}

func (x *ApplyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyPolicyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApplyPolicyRequest) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

type ApplyPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyResponse) Reset() {
	*x = ApplyPolicyResponse{}
	mi := &file_enclave_api_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyResponse) ProtoMessage() {}

func (x *ApplyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_api_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_enclave_api_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyPolicyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_enclave_api_v1_agent_proto protoreflect.FileDescriptor

const file_enclave_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aenclave/api/v1/agent.proto\x12\bagent.v1\"^\n" +
	"\fStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04vcpu\x18\x02 \x01(\x05R\x04vcpu\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\"i\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\"\xc8\x01\n" +
	"\vToolRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x12!\n" +
	"\fcontext_json\x18\x06 \x01(\tR\vcontextJson\"\x92\x01\n" +
	"\fToolResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x127\n" +
	"\fsyscall_logs\x18\x04 \x03(\v2\x14.agent.v1.SyscallLogR\vsyscallLogs\"\xd2\x02\n" +
	"\n" +
	"SyscallLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x03 \x01(\tR\x04args\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12!\n" +
	"\fexecution_id\x18\t \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vorigin_kind\x18\n" +
	" \x01(\tR\n" +
	"originKind\x124\n" +
	"\x16origin_conversation_id\x18\v \x01(\tR\x14originConversationId\",\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x13GetAuditLogsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"@\n" +
	"\x14GetAuditLogsResponse\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.agent.v1.SyscallLogR\x04logs\"T\n" +
	"\x12ApplyPolicyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vpolicy_yaml\x18\x02 \x01(\tR\n" +
	"policyYaml\"E\n" +
	"\x13ApplyPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe8\x02\n" +
	"\fAgentService\x12A\n" +
	"\fStartSession\x12\x16.agent.v1.StartRequest\x1a\x19.agent.v1.SessionResponse\x12<\n" +
	"\vExecuteTool\x12\x15.agent.v1.ToolRequest\x1a\x16.agent.v1.ToolResponse\x12<\n" +
	"\vStopSession\x12\x15.agent.v1.StopRequest\x1a\x16.agent.v1.StopResponse\x12M\n" +
	"\fGetAuditLogs\x12\x1d.agent.v1.GetAuditLogsRequest\x1a\x1e.agent.v1.GetAuditLogsResponse\x12J\n" +
	"\vApplyPolicy\x12\x1c.agent.v1.ApplyPolicyRequest\x1a\x1d.agent.v1.ApplyPolicyResponseB\x18Z\x16enclave/api/v1;agentv1b\x06proto3"

var (
	file_enclave_api_v1_agent_proto_rawDescOnce sync.Once
	file_enclave_api_v1_agent_proto_rawDescData []byte
)

func file_enclave_api_v1_agent_proto_rawDescGZIP() []byte {
	file_enclave_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_enclave_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enclave_api_v1_agent_proto_rawDesc), len(file_enclave_api_v1_agent_proto_rawDesc)))
	})
	return file_enclave_api_v1_agent_proto_rawDescData
}

var file_enclave_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_enclave_api_v1_agent_proto_goTypes = []any{
	(*StartRequest)(nil),         // 0: agent.v1.StartRequest
	(*SessionResponse)(nil),      // 1: agent.v1.SessionResponse
	(*ToolRequest)(nil),          // 2: agent.v1.ToolRequest
	(*ToolResponse)(nil),         // 3: agent.v1.ToolResponse
	(*SyscallLog)(nil),           // 4: agent.v1.SyscallLog
	(*StopRequest)(nil),          // 5: agent.v1.StopRequest
	(*StopResponse)(nil),         // 6: agent.v1.StopResponse
	(*GetAuditLogsRequest)(nil),  // 7: agent.v1.GetAuditLogsRequest
	(*GetAuditLogsResponse)(nil), // 8: agent.v1.GetAuditLogsResponse
	(*ApplyPolicyRequest)(nil),   // 9: agent.v1.ApplyPolicyRequest
	(*ApplyPolicyResponse)(nil),  // 10: agent.v1.ApplyPolicyResponse
}
var file_enclave_api_v1_agent_proto_depIdxs = []int32{
	4,  // 0: agent.v1.ToolResponse.syscall_logs:type_name -> agent.v1.SyscallLog
	4,  // 1: agent.v1.GetAuditLogsResponse.logs:type_name -> agent.v1.SyscallLog
	0,  // 2: agent.v1.AgentService.StartSession:input_type -> agent.v1.StartRequest
	2,  // 3: agent.v1.AgentService.ExecuteTool:input_type -> agent.v1.ToolRequest
	5,  // 4: agent.v1.AgentService.StopSession:input_type -> agent.v1.StopRequest
	7,  // 5: agent.v1.AgentService.GetAuditLogs:input_type -> agent.v1.GetAuditLogsRequest
	9,  // 6: agent.v1.AgentService.ApplyPolicy:input_type -> agent.v1.ApplyPolicyRequest
	1,  // 7: agent.v1.AgentService.StartSession:output_type -> agent.v1.SessionResponse
	3,  // 8: agent.v1.AgentService.ExecuteTool:output_type -> agent.v1.ToolResponse
	6,  // 9: agent.v1.AgentService.StopSession:output_type -> agent.v1.StopResponse
	8,  // 10: agent.v1.AgentService.GetAuditLogs:output_type -> agent.v1.GetAuditLogsResponse
	10, // 11: agent.v1.AgentService.ApplyPolicy:output_type -> agent.v1.ApplyPolicyResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_enclave_api_v1_agent_proto_init() }
func file_enclave_api_v1_agent_proto_init() {
	if File_enclave_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enclave_api_v1_agent_proto_rawDesc), len(file_enclave_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enclave_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_enclave_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_enclave_api_v1_agent_proto_msgTypes,
	}.Build()
	File_enclave_api_v1_agent_proto = out.File
	file_enclave_api_v1_agent_proto_goTypes = nil
	file_enclave_api_v1_agent_proto_depIdxs = nil
}
