// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: enclave/api/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "enclave/api/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceStartSessionProcedure is the fully-qualified name of the AgentService's StartSession
	// RPC.
	AgentServiceStartSessionProcedure = "/agent.v1.AgentService/StartSession"
	// AgentServiceExecuteToolProcedure is the fully-qualified name of the AgentService's ExecuteTool
	// RPC.
	AgentServiceExecuteToolProcedure = "/agent.v1.AgentService/ExecuteTool"
	// AgentServiceStopSessionProcedure is the fully-qualified name of the AgentService's StopSession
	// RPC.
	AgentServiceStopSessionProcedure = "/agent.v1.AgentService/StopSession"
	// AgentServiceGetAuditLogsProcedure is the fully-qualified name of the AgentService's GetAuditLogs
	// RPC.
	AgentServiceGetAuditLogsProcedure = "/agent.v1.AgentService/GetAuditLogs"
	// AgentServiceApplyPolicyProcedure is the fully-qualified name of the AgentService's ApplyPolicy
	// RPC.
	AgentServiceApplyPolicyProcedure = "/agent.v1.AgentService/ApplyPolicy"
)

// AgentServiceClient is a client for the agent.v1.AgentService service.
type AgentServiceClient interface {
	// Spawns a new secure microVM
	StartSession(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.SessionResponse], error)
	// Sends a tool execution request to a specific VM
	ExecuteTool(context.Context, *connect.Request[v1.ToolRequest]) (*connect.Response[v1.ToolResponse], error)
	// Force kills a VM (Panic Button)
	// Force kills a VM (Panic Button)
	StopSession(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error)
	// Read-Path: Query aggregated audit logs
	GetAuditLogs(context.Context, *connect.Request[v1.GetAuditLogsRequest]) (*connect.Response[v1.GetAuditLogsResponse], error)
	// Dynamic Policy Injection (Vsock)
	ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error)
}

// NewAgentServiceClient constructs a client for the agent.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_enclave_api_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		startSession: connect.NewClient[v1.StartRequest, v1.SessionResponse](
			httpClient,
			baseURL+AgentServiceStartSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		executeTool: connect.NewClient[v1.ToolRequest, v1.ToolResponse](
			httpClient,
			baseURL+AgentServiceExecuteToolProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ExecuteTool")),
			connect.WithClientOptions(opts...),
		),
		stopSession: connect.NewClient[v1.StopRequest, v1.StopResponse](
			httpClient,
			baseURL+AgentServiceStopSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StopSession")),
			connect.WithClientOptions(opts...),
		),
		getAuditLogs: connect.NewClient[v1.GetAuditLogsRequest, v1.GetAuditLogsResponse](
			httpClient,
			baseURL+AgentServiceGetAuditLogsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAuditLogs")),
			connect.WithClientOptions(opts...),
		),
		applyPolicy: connect.NewClient[v1.ApplyPolicyRequest, v1.ApplyPolicyResponse](
			httpClient,
			baseURL+AgentServiceApplyPolicyProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ApplyPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	startSession *connect.Client[v1.StartRequest, v1.SessionResponse]
	executeTool  *connect.Client[v1.ToolRequest, v1.ToolResponse]
	stopSession  *connect.Client[v1.StopRequest, v1.StopResponse]
	getAuditLogs *connect.Client[v1.GetAuditLogsRequest, v1.GetAuditLogsResponse]
	applyPolicy  *connect.Client[v1.ApplyPolicyRequest, v1.ApplyPolicyResponse]
}

// StartSession calls agent.v1.AgentService.StartSession.
func (c *agentServiceClient) StartSession(ctx context.Context, req *connect.Request[v1.StartRequest]) (*connect.Response[v1.SessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// ExecuteTool calls agent.v1.AgentService.ExecuteTool.
func (c *agentServiceClient) ExecuteTool(ctx context.Context, req *connect.Request[v1.ToolRequest]) (*connect.Response[v1.ToolResponse], error) {
	return c.executeTool.CallUnary(ctx, req)
}

// StopSession calls agent.v1.AgentService.StopSession.
func (c *agentServiceClient) StopSession(ctx context.Context, req *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error) {
	return c.stopSession.CallUnary(ctx, req)
}

// GetAuditLogs calls agent.v1.AgentService.GetAuditLogs.
func (c *agentServiceClient) GetAuditLogs(ctx context.Context, req *connect.Request[v1.GetAuditLogsRequest]) (*connect.Response[v1.GetAuditLogsResponse], error) {
	return c.getAuditLogs.CallUnary(ctx, req)
}

// ApplyPolicy calls agent.v1.AgentService.ApplyPolicy.
func (c *agentServiceClient) ApplyPolicy(ctx context.Context, req *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error) {
	return c.applyPolicy.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the agent.v1.AgentService service.
type AgentServiceHandler interface {
	// Spawns a new secure microVM
	StartSession(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.SessionResponse], error)
	// Sends a tool execution request to a specific VM
	ExecuteTool(context.Context, *connect.Request[v1.ToolRequest]) (*connect.Response[v1.ToolResponse], error)
	// Force kills a VM (Panic Button)
	// Force kills a VM (Panic Button)
	StopSession(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error)
	// Read-Path: Query aggregated audit logs
	GetAuditLogs(context.Context, *connect.Request[v1.GetAuditLogsRequest]) (*connect.Response[v1.GetAuditLogsResponse], error)
	// Dynamic Policy Injection (Vsock)
	ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_enclave_api_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceStartSessionHandler := connect.NewUnaryHandler(
		AgentServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(agentServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceExecuteToolHandler := connect.NewUnaryHandler(
		AgentServiceExecuteToolProcedure,
		svc.ExecuteTool,
		connect.WithSchema(agentServiceMethods.ByName("ExecuteTool")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStopSessionHandler := connect.NewUnaryHandler(
		AgentServiceStopSessionProcedure,
		svc.StopSession,
		connect.WithSchema(agentServiceMethods.ByName("StopSession")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAuditLogsHandler := connect.NewUnaryHandler(
		AgentServiceGetAuditLogsProcedure,
		svc.GetAuditLogs,
		connect.WithSchema(agentServiceMethods.ByName("GetAuditLogs")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceApplyPolicyHandler := connect.NewUnaryHandler(
		AgentServiceApplyPolicyProcedure,
		svc.ApplyPolicy,
		connect.WithSchema(agentServiceMethods.ByName("ApplyPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceStartSessionProcedure:
			agentServiceStartSessionHandler.ServeHTTP(w, r)
		case AgentServiceExecuteToolProcedure:
			agentServiceExecuteToolHandler.ServeHTTP(w, r)
		case AgentServiceStopSessionProcedure:
			agentServiceStopSessionHandler.ServeHTTP(w, r)
		case AgentServiceGetAuditLogsProcedure:
			agentServiceGetAuditLogsHandler.ServeHTTP(w, r)
		case AgentServiceApplyPolicyProcedure:
			agentServiceApplyPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) StartSession(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.SessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentService.StartSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) ExecuteTool(context.Context, *connect.Request[v1.ToolRequest]) (*connect.Response[v1.ToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentService.ExecuteTool is not implemented"))
}

func (UnimplementedAgentServiceHandler) StopSession(context.Context, *connect.Request[v1.StopRequest]) (*connect.Response[v1.StopResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentService.StopSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAuditLogs(context.Context, *connect.Request[v1.GetAuditLogsRequest]) (*connect.Response[v1.GetAuditLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentService.GetAuditLogs is not implemented"))
}

func (UnimplementedAgentServiceHandler) ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.AgentService.ApplyPolicy is not implemented"))
}
